matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
    - os: windows
      filter_secrets: false
      language: cpp

before_install:
  - git submodule update --init --recursive

script:
  - mkdir build && cd build

  - echo 'cmake' && echo -en 'travis_fold:start:script.cmake\\r'
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake .. -G "Visual Studio 15 2017 Win64" ; else cmake .. ; fi
  - echo -en 'travis_fold:end:script.cmake\\r'

  - echo 'build' && echo -en 'travis_fold:start:script.build\\r'
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake --build . --target ALL_BUILD --config Release ; else make -j2 ; fi
  - echo -en 'travis_fold:end:script.build\\r'

  - echo 'run' && echo -en 'travis_fold:start:script.run\\r'
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./bin/Release/cpp-sandbox ; else ./bin/cpp-sandbox ; fi
  - echo -en 'travis_fold:end:script.run\\r'
